name: link
description: A simple widget for simulating links in Flutter
version: 1.0.0
# homepage: https://www.example.com
author: Germán Alonso <galonsos@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.0.2

dev_dependencies:
  test: ^1.0.0
